// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: true,
  // baseUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/',
  // placeListUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/list',
  // placeCardUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/card/',
  // authUserUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/auth/authenticate',
  // createUserUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/user/create',
  // modifyUserUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/user/modify',
  // deleteUserUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/user/delete',
  // addFavoriteUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/favorites/add',
  // removeFavoriteUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/favorites/remove',
  // listFavoriteUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/favorites/list',
  // createPlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/create',
  // typePlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/type/list',
  // tagsPlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/tags/list',
  // restrictionsPlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/restrictions/list',
  // pendingPlacesUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/pending-places',
  // updateStatusPlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/update-status',
  // updateAllStatusPlaceUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/places/update-all-status',
  // valuationsListUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/valuations',
  // createValuationsUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/valuations/create',
  // alreadyValuatedUrl: 'http://petradar-api-1256.eu-west-3.elasticbeanstalk.com/valuations',


  //'http://127.0.0.1:5000/',

  baseUrl: 'http://127.0.0.1:5000/',
  placeListUrl: 'http://127.0.0.1:5000/places/list',
  placeCardUrl: 'http://127.0.0.1:5000/places/card/',
  authUserUrl: 'http://127.0.0.1:5000/auth/authenticate',
  createUserUrl: 'http://127.0.0.1:5000/user/create',
  modifyUserUrl: 'http://127.0.0.1:5000/user/modify',
  deleteUserUrl: 'http://127.0.0.1:5000/user/delete',
  addFavoriteUrl: 'http://127.0.0.1:5000/favorites/add',
  removeFavoriteUrl: 'http://127.0.0.1:5000/favorites/remove',
  listFavoriteUrl: 'http://127.0.0.1:5000/favorites/list',
  createPlaceUrl: 'http://127.0.0.1:5000/places/create',
  typePlaceUrl: 'http://127.0.0.1:5000/type/list',
  tagsPlaceUrl: 'http://127.0.0.1:5000/tags/list',
  restrictionsPlaceUrl: 'http://127.0.0.1:5000/restrictions/list',
  pendingPlacesUrl: 'http://127.0.0.1:5000/places/pending-places',
  updateStatusPlaceUrl: 'http://127.0.0.1:5000/places/update-status',
  updateAllStatusPlaceUrl: 'http://127.0.0.1:5000/places/update-all-status',
  updateAverageRatingUrl: 'http://127.0.0.1:5000/places/update-rating',
  valuationsListUrl: 'http://127.0.0.1:5000/valuations',
  createValuationsUrl: 'http://127.0.0.1:5000/valuations/create',
  alreadyValuatedUrl: 'http://127.0.0.1:5000/valuations',

  iconUrl: 'assets/icons/',
  defaultLatitude: 37.36247679369061,
  defaultLongitude: -6.034726252104273,
};