export enum PermissionEnum {
    CREATE_PLACE = 'CREATE_PLACE',
    FAVORITE_PLACE = 'FAVORITE_PLACE',
    MODIFY_USER = 'MODIFY_USER',
    DELETE_USER = 'DELETE_USER',
    ACCEPT_PLACE = 'ACCEPT_PLACE',
    DECLINE_PLACE = 'DECLINE_PLACE'
}