export enum TypeEnum {
    MALL = 'MALL',
    PARK = 'PARK',
    RESTURANT = 'RESTURANT',
    SUPERMARKET = 'SUPERMARKET',
    HOTEL = 'HOTEL',
    COFFESHOP = 'COFFESHOP',
    DOGTRAINER ='DOGTRAINER',
    VETERINARY = 'VETERINARY',
    HAIRDRESSER = 'HAIRDRESSER'
}